language: java
jdk:
  - openjdk11
branches:
  only:
    - master

# travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r bootAwsProject *
  - mkdir -p deploy
  - mv bootAwsProject.zip deploy/bootAwsProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 등록 변수
    secret_access_key: $AWS_SECRET_KEY
    bucket: hoo788-springboot2-webserive-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토라
    wait-until-deployed: true

# when CI complete, alarm send email
notifications:
  email:
    recipients:
      - hoo788@gmail.com